<h1>PitchBladeDemo</h1>
<p>Welcome to the demo application of the PitchBlade framework.</p>
<p>PitchBlade is an <a href="https://github.com/PeeHaa" target="_blank">open-source project</a> maintained by <a href="https://github.com/PeeHaa" target="_blank">Pieter Hordijk</a>.</p>
<p>It is meant to rapidly create prototypes of webapplications in PHP 5.4+.</p>
<p>Some key features of PitchBlade include:</p>
<ul>
    <li>Solid library to aid you developing webapplications</li>
    <li>Very loosely coupled components</li>
    <li>100% unit tested</li>
    <li>SOLID object oriented design</li>
    <li>Provides (but doesn't force you to use) a layer to easily implement a separation of concerns design through: MVC, MVP or MVVM</li>
    <li>Provides a routing system for SEO friendly URLs</li>
</ul>
